0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,23 +1,28 @@
 #!/usr/bin/env bash
-
 # Check if correct number of parameters are passed
-if [ "$#" -lt 4 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+
+usage() {
+	    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	        exit 1
+	}
+
+# Check if number of parameters is less than 3
+if [ $# -lt 4 ]; then
+	    usage
 fi
 
 # Assign parameters to variables
-file_path=$1
-server_ip=$2
-username=$3
-ssh_key=$4
+path_to_file="$1"
+ip="$2"
+username="$3"
+ssh_key="$4"
 
-# Transfer the file using scp
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/
+# Transfer file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$ip":~/
 
 # Check if scp command was successful
 if [ $? -eq 0 ]; then
-    echo "File transferred successfully."
-else
-    echo "Error: File transfer failed."
+	    echo "File transfer successful"
+    else
+	        echo "File transfer failed"
 fi
