0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,25 +1,26 @@
 #!/usr/bin/env bash
-# Check if correct number of parameters are passed
-
-
-if [ $# -lt 4 ]; then
-
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	  exit 1
+# Checking for command-line argument
+if [ $# -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-# Assign parameters to variables
-path_to_file="$1"
-ip="$2"
-username="$3"
-ssh_key="$4"
+# Assigning Arguments to variables
 
-# Transfer file using scp
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$ip":~/
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
 
-# Check if scp command was successful
-if [ $? -eq 0 ]; then
-	    echo "File transfer successful"
-    else
-	        echo "File transfer failed"
+
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
+else
+  echo "FILE TRANSFER FAILED"
 fi
